name: Setup Luca
description: Install the Luca CLI and optionally install project tools from a spec file, adding them to PATH.

branding:
  icon: package
  color: blue

inputs:
  version:
    description: >
      The version of Luca to install (e.g. "1.2.3"). Omit to install the
      latest release. When provided, a `.luca-version` file is written
      before the install script runs so the existing version-detection
      logic in the install script picks it up automatically.
    required: false
    default: ""
  spec:
    description: >
      Path to the Luca spec file, relative to the workspace root
      (e.g. "Lucafile" or "config/Lucafile-ci"). When provided, tools
      are installed and added to PATH. Omit to skip tool installation.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Write .luca-version (when version is pinned)
      if: inputs.version != ''
      shell: bash
      run: echo "${{ inputs.version }}" > .luca-version

    - name: Install Luca CLI
      shell: bash
      run: curl -fsSL https://luca.tools/install.sh | bash

    - name: Install tools
      if: inputs.spec != ''
      shell: bash
      run: |
        luca install --spec=${{ inputs.spec }}
        echo "$PWD/.luca/active" >> $GITHUB_PATH
